### ISSUE TITLE
Add readme file for how to run this project

### ISSUE THREAD

**Issue by Mustafiz04** [GlobeHoppin/globe-hoppin-backend#14]

**Comment by anchalchaturvedi08** [comment]
Issue Title: Update README File

Description: 
Add a project overview, setup instructions, usage examples, contribution guidelines, and relevant images to improve the README file.

Would you @Mustafiz04 like me to assign this issue to you?

**Comment by Mustafiz04** [comment]
Please write everything briefly. 
Also update `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` file

**Comment by anchalchaturvedi08** [comment]
Sure, thank you for assigning this to me.
