### ISSUE TITLE
Add an Api to the contact form  

### ISSUE THREAD

**Issue by AyushSharma72** [GlobeHoppin/globe-hoppin-backend#16]
i will add an api which lets you receive the messages of anyone who submit the contact form

**Comment by AyushSharma72** [comment]
hey can u please label this issue as  **level 3**

**Comment by AyushSharma72** [comment]
please provide your email on which you want to recieve the messages

**Comment by Mustafiz04** [comment]
@AyushSharma72 
mustafizkaifee04+globehoppin@gmail.com

**Comment by AyushSharma72** [comment]
hey @Mustafiz04  the correct level is **level2**  and not **level 2** please change
