### ISSUE TITLE
User Profile APIs

### ISSUE THREAD

**Issue by Mustafiz04** [GlobeHoppin/globe-hoppin-backend#8]
Add API for user profile functionality

- [ ] 1. Create a new profile
- [ ] 2. Edit profile information
- [ ] 3. Get profile details

I'll be sure to add more details soon.

**Comment by haseebzaki-07** [comment]
Hey @Mustafiz04 I want to work on this issue

**Comment by Mustafiz04** [comment]
Now you have two tasks.

**Comment by haseebzaki-07** [comment]
Sure I will do it!
